Sprint 9. Attempt №1
ppxxd/java-filmorate pull request #6
Opened 2024-03-23 19:30 UTC by ppxxd

<feat>: UserController and FilmController for REST;
<feat>: Film and User classes;

2024-03-25 08:06 UTC, mikita95 requested changes
Все сделано отлично:) Оставил лишь небольшие замечания

2024-03-25 08:06 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final Map<Integer, Film> films = new HashMap<>();
Лучше было бы вынести хранение данных в отдельные классы-сервисы, так ответственности были бы разделены

2024-03-25 08:06 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +//    @JsonDeserialize(using = LocalDateDeserializer.class)
Закомментированного кода быть не должно

2024-03-26 10:01 UTC, ppxxd commented
Убрал комментарии и вынес хранение мапы в пакет storages. Вроде теперь должно быть всё ок :)

2024-03-26 15:03 UTC, mikita95 approved these changes
Все отлично:) Можно мержить пул-реквест

2024-03-26 15:42 UTC, merged