feat: DAO and DAL;
ppxxd/java-filmorate pull request #8
Opened 2024-04-23 07:01 UTC by ppxxd

feat: Unit tests;
feat: Updated old code;

2024-04-23 07:06 UTC, ppxxd commented
Снова всё в последний момент, к сожалению. Код местами не идеальный, наверное, но всё равно надеюсь на возможность сразу закрыть ФЗ с первой попытки :)

2024-04-24 07:34 UTC, mikita95 requested changes
Все отлично :) Оставил лишь небольшие замечания

2024-04-24 07:34 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        System.out.println(userService.getUserFriends(id) + " " + id);
Лучше писать в лог, в консоли сообщение может потеряться

2024-04-24 07:34 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/exception/AlreadyFriendsException.java
> +    public String getMessage() {
Этот метод можно просто удалить, он и так есть

2024-04-24 07:34 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/film/impl/FilmLikesDaoImpl.java
> +        String sql = "INSERT INTO film_likes (film_id, user_id) VALUES (?, ?)";
Лучше использовать оператор merge, так не возникнет ошибки при повторном вызове этого метода для одних и тех же данных

2024-04-25 11:31 UTC, mikita95 approved these changes
Все отлично :) Можно мержить пул-реквест

2024-04-25 11:55 UTC, merged